# Generated by Django 4.0.2 on 2022-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
