# Generated by Django 4.0.2 on 2022-02-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_name_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
