# Generated by Django 4.0.2 on 2022-02-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_user_id_profile_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='patient',
            new_name='user',
        ),
    ]
